name: Python Behave

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Always use the latest stable version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Download and extract Allure CLI from GitHub releases
        curl -o allure.zip -Ls https://github.com/allure-framework/allure-core/releases/latest/download/allure-commandline.zip
        7z x allure.zip -oallure_temp
        mv allure_temp/* allure_temp/.??* .  # Move all files including hidden files
        rm -rf allure_temp allure.zip

    - name: Change directory and run tests
      run: |
        cd test_runners
        if (Test-Path "test_runner.bat") {
          .\test_runner.bat "features/feature1.feature" @Test1
        } else {
          Write-Host "test_runner.bat not found."
          exit 1
        }
