name: Python Behave

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Always use the latest stable version of Python 3

    - name: Install Allure CLI
      run: |
        # Download Allure CLI
        Invoke-WebRequest -Uri 'https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip' -OutFile 'allure.zip'
        
        # Extract Allure CLI
        Expand-Archive -Path 'allure.zip' -DestinationPath 'allure_temp'
        
        # Move Allure CLI files to appropriate directory
        Move-Item -Path 'allure_temp\*' -Destination '.\' -Force
    
        # Cleanup: Remove downloaded zip file and temporary directory
        Remove-Item -Path 'allure.zip'
        Remove-Item -Path 'allure_temp' -Recurse
    
    - name: Run Allure Command
      run: |
        # List contents of current directory for debugging
        Get-ChildItem -Path .
    
        # Run Allure command
        echo "Allure Report Version: "
        .\allure-2.29.0\bin\allure --version


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Change directory and run tests
      run: |
        cd test_runners
        if (Test-Path "test_runner_pipeline.bat") {
          .\test_runner.bat "features/feature1.feature" @Test1
        } else {
          Write-Host "test_runner_pipeline.bat not found."
          exit 1
        }
        # List contents of current directory for debugging
        Get-ChildItem -Path .

    - name: Generate Allure Report
      run: |
        # List contents of current directory for debugging
        Get-ChildItem -Path .
        .\allure-2.29.0\bin\allure generate test-results/allure-report-json/ -o test-results/allure-report/ --report-name "Test Result" --clean

    - name: Rename Allure Report
      run: |
        # List contents of current directory for debugging
        Get-ChildItem -Path .
    
        # Check if the index.html file exists in the allure-report directory
        if Test-Path "test-results\allure-report\index.html" {
          # Rename the index.html file to "Automation Test Execution Report.html"
          Rename-Item -Path "test-results\allure-report\index.html" -NewName "Automation Test Execution Report.html" -ErrorAction Stop
    
          # Output a message indicating successful renaming
          Write-Output "Allure report successfully renamed."
        } else {
          # Output an error message if the index.html file doesn't exist
          Write-Error "The index.html file does not exist in the allure-report directory."
        }
        cd test-results
        cd allure-report
        Get-ChildItem -Path .

