name: Python Behave

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Always use the latest stable version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Change directory and run tests
      run: |
        cd test_runners
        test_runner.bat "features/feature1.feature" @Test1
